# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mac/Documents/iSource/mysql-5.6.42

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mac/Documents/iSource/mysql-5.6.42

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Client\" \"DataFiles\" \"DebugBinaries\" \"Development\" \"Documentation\" \"Embedded\" \"Info\" \"IniFiles\" \"ManPages\" \"Readme\" \"Server\" \"Server_Scripts\" \"SharedLibraries\" \"SqlBench\" \"SupportFiles\" \"Test\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.13.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && /usr/local/Cellar/cmake/3.13.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/mac/Documents/iSource/mysql-5.6.42/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && /usr/local/Cellar/cmake/3.13.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Documents/iSource/mysql-5.6.42/CMakeFiles /Users/mac/Documents/iSource/mysql-5.6.42/storage/spartan/CMakeFiles/progress.marks
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f CMakeFiles/Makefile2 storage/spartan/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Documents/iSource/mysql-5.6.42/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f CMakeFiles/Makefile2 storage/spartan/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f CMakeFiles/Makefile2 storage/spartan/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f CMakeFiles/Makefile2 storage/spartan/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
storage/spartan/CMakeFiles/spartan.dir/rule:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f CMakeFiles/Makefile2 storage/spartan/CMakeFiles/spartan.dir/rule
.PHONY : storage/spartan/CMakeFiles/spartan.dir/rule

# Convenience name for target.
spartan: storage/spartan/CMakeFiles/spartan.dir/rule

.PHONY : spartan

# fast build rule for target.
spartan/fast:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/build
.PHONY : spartan/fast

ha_spartan.o: ha_spartan.cc.o

.PHONY : ha_spartan.o

# target to build an object file
ha_spartan.cc.o:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/ha_spartan.cc.o
.PHONY : ha_spartan.cc.o

ha_spartan.i: ha_spartan.cc.i

.PHONY : ha_spartan.i

# target to preprocess a source file
ha_spartan.cc.i:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/ha_spartan.cc.i
.PHONY : ha_spartan.cc.i

ha_spartan.s: ha_spartan.cc.s

.PHONY : ha_spartan.s

# target to generate assembly for a file
ha_spartan.cc.s:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/ha_spartan.cc.s
.PHONY : ha_spartan.cc.s

spartan_data.o: spartan_data.cc.o

.PHONY : spartan_data.o

# target to build an object file
spartan_data.cc.o:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/spartan_data.cc.o
.PHONY : spartan_data.cc.o

spartan_data.i: spartan_data.cc.i

.PHONY : spartan_data.i

# target to preprocess a source file
spartan_data.cc.i:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/spartan_data.cc.i
.PHONY : spartan_data.cc.i

spartan_data.s: spartan_data.cc.s

.PHONY : spartan_data.s

# target to generate assembly for a file
spartan_data.cc.s:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(MAKE) -f storage/spartan/CMakeFiles/spartan.dir/build.make storage/spartan/CMakeFiles/spartan.dir/spartan_data.cc.s
.PHONY : spartan_data.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... spartan"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... ha_spartan.o"
	@echo "... ha_spartan.i"
	@echo "... ha_spartan.s"
	@echo "... spartan_data.o"
	@echo "... spartan_data.i"
	@echo "... spartan_data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/mac/Documents/iSource/mysql-5.6.42 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

